### ISSUE TITLE
Mode_Base.H

### ISSUE THREAD

**Issue by scousethief** [nlamprian/ArduinoPixel#5]
Hi, sorry new to this. An ESP32 . Trying to compile i constantly get the below error message.  Mode_base.h is in the correct directory and i can see it in the arduino sketch window.

led_strip_base.h:32:28: error: mode/mode_base.h: No such file or directory

compilation terminated.

exit status 1
mode/mode_base.h: No such file or directory

**Comment by nlamprian** [comment]
Please move the ArduinoPixel folder into your Arduino libraries folder. That should do the trick.
